# Generated by Django 3.1.2 on 2020-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='blog',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', to='app01.blog'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatar/default.jpg', upload_to='avatar/', verbose_name='默认头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
    ]
